// Catálogo completo de embajadas y consulados.
// Fuente: listado oficial del Ministerio de Relaciones Exteriores.
// Usado por prisma/seed.ts (npm run db:seed).

export interface ConsulateSeed {
  type: string;
  region: string;
  country: string;
  location: string;
  address: string;
}

export const CONSULATES: ConsulateSeed[] = [
  { type: 'EMBAJADA', region: 'América del Norte', country: 'CANADÁ', location: 'Ottawa, Ontario', address: '209 Kent Street, K2P 1Z8, Ottawa, Ontario' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'CANADÁ', location: 'Montreal, Québec', address: '2055 Rue Peel, Oficina 840, Montreal, Quebec, H3A-1V4' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'CANADÁ', location: 'Toronto, Ontario', address: '425 Bloor Street East Suite 510 Código Postal M4W3R4, Toronto' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'CANADÁ', location: 'Vancouver, Columbia Británica', address: '1111 Melville Street, Suite 602, Vancouver, BC, V6E 3V6' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'CANADÁ', location: 'Calgary, Provincia de Alberta', address: '505 3rd Street SW Suite 1730, Calgary, Alberta T2P 3E6.' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'CANADÁ', location: 'Winnipeg, Manitoba', address: '205-233 Portage Ave Winnipeg, Manitoba R3B 2A7' },
  { type: 'EMBAJADA', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Washington, D.C.', address: '1400 Sixteenth Street, N.W., Suite 100, Washington, D.C. 20036' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Wisconsin Ave NW, Washington D.C.', address: '2332 Wisconsin Ave NW, Washington, DC 20007, Estados Unidos' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Boston, Massachusetts', address: '46 Bennington Street East Boston, MA 02128' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Chicago, Illinois', address: '177 North State Street, 2do. Piso Mezzanine, Chicago, IL 60601' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Doral, Florida', address: '8550 NW 33rd Street, Suite 100, Doral, FL 33122-1941' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Dallas, Texas', address: '7610 Stemmons Fwy. Suite 400, Dallas, Texas 75247' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'McAllen, Condado de Hidalgo, Texas.', address: '701 S. Broadway St., McAllen, TX. 78501' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Laredo, Texas', address: '6010 McPherson Rd. Ste #140, Laredo, Texas, 78041.' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Houston, Texas', address: '8300 Bissonnet St, Suite 400 Houston, TX 77074' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'El Paso, Texas', address: '400 W. San Antonio St Suite B, El Paso, TX 79901' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Elizabeth, New Jersey', address: '40 Parker Road, Suite 100, Elizabeth, NJ 07208' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Las Vegas, Nevada', address: '765 N. Nellis Blvd, Suite C-5, Las Vegas, NV, 89110' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Aurora, Colorado', address: '1450 S. Havana St. Suite 100, Aurora, CO, 80012' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Los Ángeles, California', address: '3250 Wilshire Blvd. Suite 550, Los Ángeles, CA, 90010' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Long Island, New York', address: '151 Alkier St. Brentwood, NY 11717' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Nueva York, NY', address: '46 Park Avenue, New York, NY, 10016.' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'San Francisco, California', address: '507 Polk Street, Suite 280, San Francisco, CA, 94102' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'San Bernardino, California', address: '3505 Highland Ave, Highland, CA 92346, Estados Unidos' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Seattle, Washington', address: 'Broderick Building 615, Second Ave. Suite # 50, Seattle, WA 98104' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Tucson, Arizona', address: '1039 N. 6th Ave., Tucson, AZ, 85705' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Silver Spring, Maryland', address: '926 Philadelphia Ave. Silver Spring, MD, 20910' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Duluth, Atlanta', address: '3550 Corporate Way, Suite A, Duluth, GA 30096' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Woodbridge, Virginia', address: '14572 Potomac, Mills Road, Woodbridge, VA, 22192' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Charlotte, Carolina del Norte.', address: '1520 West Boulevard Suite "C, Charlotte, N.C. 28208' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Saint Paul, Minnesota', address: '60 PLAZA BLVD E. SUITE 150 ST PAUL MN 55107 USA' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Springdale, Arkansas', address: '3875 W Sunset Ave, Springdale, AR 72762, Estados Unidos' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Fresno, California', address: '49 W. Alluvial Ave. Fresno, CA, 93650' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Nashville, Tennessee', address: '311 Plus Park Blvd, Suite 110, Nashville, TN 37217' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Omaha, Nebraska', address: '11422 Miracle Hills DR Suite 205 Omaha, Nebraska' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'Salt Lake City, Utah', address: '124 S 400 E STE 410 SALT LAKE CITY UT 84111-2186 USA 84111' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'ESTADOS UNIDOS', location: 'San Antonio, Texas', address: '12521 Nacogdoches Road, suite 102, San Antonio, Texas, 78217.' },
  { type: 'EMBAJADA', region: 'América del Norte', country: 'MÉXICO', location: 'México', address: 'Calle Temístocles 88, Colonia Polanco, Delegación Miguel Hidalgo, C.P. 11560, Ciudad de México' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Monterrey, Nuevo León', address: 'Calle Montes Cárpatos, N°. 320. Esquina con Calle Cerro de la Luz, Residencial San Agustín, San Pedro Garza-García, Nuevo León, Monterrey, C.P. 66260.' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Tijuana, Baja California', address: 'Brigoz Corporativo, interior 303, José María Velazco #2789, Zona Urbana Río Tijuana, Baja California, CP 22010' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Ciudad Juárez, Chihuahua', address: 'Avenida Abraham Lincoln #1126, Local 5 FRACCTO. La Playa III, Condominio Lincoln, Código Postal 32317, Ciudad Juárez, Chihuahua' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Tapachula, Chiapas', address: 'Avenida Central Norte, S/N entre 37 y 39 calle poniente, Colonia 5 de Febrero, Tapachula, Chipas. Código Postal: 30710' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Acayucan, Veracruz', address: 'Calle Melchor Ocampo Norte, N° 1212, Ciudad de Acayucan, Veracruz, C.P. 96000' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'San Luis Potosí', address: 'Calle Avanzada N° 513, entre V. Carranza y Quintana Roo, Barrio Tequisquiapán, Código Postal 78250, San Luís Potosí' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Guadalajara', address: 'Av. Ignacio Luis Vallarta 3233, local F-12 Vallarta Poniente 44110 Guadalajara México' },
  { type: 'CONSULADO', region: 'América del Norte', country: 'MÉXICO', location: 'Oaxaca, Oaxaca', address: 'Colonia Reforma, Calle Violetas, N° 505-B, C.P. 68050, Oax, Mex.' },
  
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'BELICE', location: 'Belmopán', address: '20 Tangerine St., Cohune Walk Area, Belmopan. Dirección Postal: P.O. Box 215, Belmopán' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'COSTA RICA', location: 'San José', address: 'Del restaurante Mcdonald´s de Plaza del Sol, 7 cuadras sur y 50 metros este, Curridabat, San José' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'GUATEMALA', location: 'Guatemala', address: '15ª Avenida, 12-01, Zona 13 Ciudad de Guatemala' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'HONDURAS', location: 'Tegucigalpa', address: 'Colonia Rubén Darío, calle Froylán Turcios No. 2144 Tegucigalpa, M.D.C. Honduras. C.A.' },
  { type: 'CONSULADO', region: 'Centroamérica y el Caribe', country: 'HONDURAS', location: 'Choluteca', address: 'Barrio El Centro, Costado Norte del Parque Valle, Choluteca' },
  { type: 'CONSULADO', region: 'Centroamérica y el Caribe', country: 'HONDURAS', location: 'San Pedro Sula', address: 'Edificio Park Plaza, Local 10, 11 Av., entre 5ª. y 6ª. Calle N.O. del Barrio Guamilito, San Pedro Sula' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'NICARAGUA', location: 'Managua', address: '9 ½, Carretera a Masaya. Residencial Las Colinas, Av. Del Campo, Pasaje Los Cerros, 142, Managua' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'PANAMÁ', location: 'Panamá', address: 'Av. Anastasio Ruiz. Duplex 6, Urbanización Marbella, Frente a Escuela Japonesa Panamá. Apartado Postal 0823 -05432' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'CUBA', location: 'La Habana', address: 'Calle 24, 307, entre 3ª. y 5ª. Miramar, Playa, Ciudad de La Habana' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'REPÚBLICA DOMINICANA', location: 'Santo Domingo', address: 'Calle Itzamana No. 22, Los Cacicazgos, Santo Domingo' },
  { type: 'EMBAJADA', region: 'Centroamérica y el Caribe', country: 'TRINIDAD Y TOBAGO', location: 'Puerto España', address: '' },
  
  { type: 'EMBAJADA', region: 'América del Sur', country: 'ARGENTINA', location: 'Buenos Aires', address: 'Calle Rodríguez Peña, N°. 1524, C.P. 1021, Capital Federal' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'BRASIL', location: 'Brasilia', address: 'SHIS QL 22 Conjunto 07, Casa 08, Lago Sul. Brasilia- Distrito Federal. CEP:71650-275' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'CHILE', location: 'Santiago', address: 'Calle Coronel 2330, 5to. Piso, Oficina 51, Providencia, Santiago de Chile' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'COLOMBIA', location: 'Bogotá', address: 'Carrera 12 # 119-51, Santa Bárbara, Bogotá, D.C.' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'ECUADOR', location: 'Quito', address: 'Avenida República de El Salvador y calle Suecia, Edificio "DELTA" 890, 6° PISO, San Francisco de Quito, Pichincha' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'PERÚ', location: 'Lima', address: 'Av. Dos de Mayo 843, San Isidro – Lima 27' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'BOLIVIA', location: 'La Paz', address: 'Avenida República de El Salvador y calle Suecia, Edificio "DELTA" 890, 6° PISO, San Francisco de Quito, Pichincha' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'URUGUAY', location: 'Montevideo', address: 'Pasaje Arq. Raúl Lerena Acevedo, N°. 1453, Punta Gorda. Código Postal: 11400, Montevideo' },
  { type: 'EMBAJADA', region: 'América del Sur', country: 'VENEZUELA', location: 'Caracas', address: 'Calle Roraima, Urbanización Chuao, municipio Baruta, Estado Miranda' },
  
  { type: 'EMBAJADA', region: 'Europa', country: 'ALEMANIA', location: 'Berlín', address: 'Hessische Strasse 11, 10115, Berlín' },
  { type: 'EMBAJADA', region: 'Europa', country: 'AUSTRIA', location: 'Viena', address: 'Prinz –Eugen –Strasse, 72/2/1, 1040 Wien' },
  { type: 'EMBAJADA', region: 'Europa', country: 'BÉLGICA', location: 'Bruselas', address: 'Rue Belliard 15-17, 5° Nivel. 1000, Bruselas' },
  { type: 'EMBAJADA', region: 'Europa', country: 'SUIZA', location: 'Ginebra', address: '65 Rue de Lausanne, 1202, Ginebra' },
  { type: 'EMBAJADA', region: 'Europa', country: 'ESPAÑA', location: 'Madrid', address: 'Paseo de la Castellana, 178, 1º D, 28046, Madrid' },
  { type: 'CONSULADO', region: 'Europa', country: 'ESPAÑA', location: 'Barcelona', address: 'Calle Sardenya 175, Planta baja local 2, 08013, Barcelona, España' },
  { type: 'CONSULADO', region: 'Europa', country: 'ESPAÑA', location: 'Sevilla', address: 'Avenida Menéndez y Pelayo, Nº8, 5ª nivel, Sevilla, Reino de España' },
  { type: 'EMBAJADA', region: 'Europa', country: 'FRANCIA', location: 'París', address: '12 Rue Galilée, 75116, Paris' },
  { type: 'EMBAJADA', region: 'Europa', country: 'REINO UNIDO', location: 'Londres', address: '2nd. Floor, 8 Dorset Square, London, NW1 6PU' },
  { type: 'EMBAJADA', region: 'Europa', country: 'ITALIA', location: 'Roma', address: 'Vía Gualtiero Castellini, 13, interno D 10, Roma' },
  { type: 'CONSULADO', region: 'Europa', country: 'ITALIA', location: 'Milán', address: 'Piazza Santa Maria Beltrade, 2, 20123, Milán, Italia' },
  { type: 'EMBAJADA', region: 'Europa', country: 'SANTA SEDE', location: 'Roma', address: 'Via Lima 10, Interno 15 , Secondo Piano, 00198 Roma, Italia' },
  { type: 'EMBAJADA', region: 'Europa', country: 'PAÍSES BAJOS', location: 'La Haya', address: 'Riouwstraat 137, 2585 HP, La Haya' },
  { type: 'EMBAJADA', region: 'Europa', country: 'RUSIA', location: 'Moscú', address: 'Mitnaya Street 3, Office 14, Moscow. 119049' },
  { type: 'EMBAJADA', region: 'Europa', country: 'SUECIA', location: 'Estocolmo', address: 'Herserudsvägen 5, 5th. Floor, 181 50, Lidingö, Stockholm' },
  
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'AUSTRALIA', location: 'Canberra', address: '3/110 Giles Street, Kingston, ACT, 2604 Canberra' },
  { type: 'CONSULADO', region: 'Asia y Oceanía', country: 'AUSTRALIA', location: 'Melbourne', address: 'Level 7, 20-22, Albert Road, South Melbourne, 3205, Victoria' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'COREA DEL SUR', location: 'Seúl', address: '20th. Floor, BuyoungTaepyung, Building # 55, Sejongdae-ro, Jung-ku, Seoul, 04513' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'CHINA', location: 'Beijing', address: 'Apartment No.101, Entrance No.1, Building No.15,Jianguomenwai DRC , Chaoyang District, Beijing, 100600' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'INDIA', location: 'Nueva Delhi', address: '8, Munirka Marg, Vasant Vihar, Nueva Delhi, 110057' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'ISRAEL', location: 'Tel-Aviv', address: '6 Hamada Street, Naor Building, 4º piso, Herzliya Pituah, 46733' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'JAPÓN', location: 'Tokio', address: '38 Kowa Building, N° 803, 4-12-24, Nishi Azabu, Minato Ku, Tokio, 106-0031' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'QATAR', location: 'Doha', address: 'Villa No. 54 A, Al Riyahd Street West Bay Lagoon, East Gate (Near of Zig Zag Towers Roundabout, West Bay), Doha' },
  { type: 'EMBAJADA', region: 'Asia y Oceanía', country: 'VIETNAM', location: 'Hanói', address: '11TH FLOOR TOWER 2 CAPITAL PLACE BUILDING NO 29 LIEU GIAI STREET NGOC KHANH BA DINH HANOI' }
];
